{"timestamp":"2025-09-17T05:57:36.500733","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-17T05:57:36.501228","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/moodle_ldap_sync_and_transform_generic.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-17T05:57:36.568371Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:57:36.568696Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:57:36.569443Z","level":"info","event":"Current task name:extract_moodle_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:57:36.569650Z","level":"info","event":"Dag name:moodle_ldap_dynamic_etl_v2","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:57:36.570829","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `get` on Connection from sdk(`airflow.sdk.Connection`) instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-09-17T05:57:36.574936","level":"info","event":"Connection Retrieved 'moodle_api'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-17T05:57:36.575223Z","level":"info","event":"Extracting Moodle data...","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:57:36.578620","level":"info","event":"Connection Retrieved 'moodle_api'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-17T05:59:50.827222","level":"warning","event":"HTTPConnectionPool(host='host.docker.internal', port=80): Max retries exceeded with url: /webservice/rest/server.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7446af09a420>, 'Connection to host.docker.internal timed out. (connect timeout=None)')) Tenacity will retry to execute the operation","logger":"airflow.task.hooks.airflow.providers.http.hooks.http.HttpHook"}
{"timestamp":"2025-09-17T05:59:50.827591","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectTimeout","exc_value":"HTTPConnectionPool(host='host.docker.internal', port=80): Max retries exceeded with url: /webservice/rest/server.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7446af09a420>, 'Connection to host.docker.internal timed out. (connect timeout=None)'))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/moodle_ldap_sync_and_transform_generic.py","lineno":86,"name":"extract_moodle_data"},{"filename":"/opt/airflow/dags/moodle_ldap_sync_and_transform_generic.py","lineno":22,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":299,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":355,"name":"run_and_check"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":347,"name":"run_and_check"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":665,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPConnectionPool(host='host.docker.internal', port=80): Max retries exceeded with url: /webservice/rest/server.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7446af09a420>, 'Connection to host.docker.internal timed out. (connect timeout=None)'))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":644,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"ConnectTimeoutError","exc_value":"(<urllib3.connection.HTTPConnection object at 0x7446af09a420>, 'Connection to host.docker.internal timed out. (connect timeout=None)')","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":207,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"TimeoutError","exc_value":"[Errno 110] Connection timed out","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":85,"name":"create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":73,"name":"create_connection"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-17T05:59:50.829245Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:59:50.829550Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:59:50.829746Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): extract_moodle_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T05:59:50.829932Z","level":"info","event":"Failure caused by HTTPConnectionPool(host='host.docker.internal', port=80): Max retries exceeded with url: /webservice/rest/server.php (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7446af09a420>, 'Connection to host.docker.internal timed out. (connect timeout=None)'))","chan":"stdout","logger":"task"}
